version: "2"

services:
    countdown:
        build: . 
        container_name: countdown
        environment:
            - NUM_WORKERS=1
            - APP_NAME=countdown
            - WSGI_MODULE=app
            - WSGI_APP=app
            - PYTHONPATH=/srv/app
            - APP_LISTEN_ON=0.0.0.0
            - APP_DEBUG=True
            - PYTHONUNBUFFERED=1
            - DB_DIR=/var/lib/countdown
        ports:
            - "8000:80/tcp"
        volumes:
            - ./data:/var/lib/countdown
        depends_on:
            - rsyslog
        logging:
            # https://docs.docker.com/config/containers/logging/syslog/
            driver: syslog
            options: 
                syslog-address: "udp://localhost:5514"
                tag: "countdown"
    rsyslog:
        image: voxxit/rsyslog 
        container_name: rsyslog
        ports:
            - "5514:514/udp"
